version: "3.3"

services:
  datanode1:
    image: go-test:latest
    command: sh -c "go run /dfs/DN.go -id 1"
    ports:
      - 11091:11091
    expose:
      - 11091
    volumes:
      - ./TinyDFS:/dfs/TinyDFS

  datanode2:
    image: go-test:latest
    command: sh -c "go run /dfs/DN.go -id 2"
    ports:
      - 11092:11092
    expose:
      - 11092
    volumes:
      - ./TinyDFS:/dfs/TinyDFS
  
  namenode:
    image: go-test:latest
    command: sh -c "go run /dfs/NN.go"
    depends_on: 
      - "datanode1"
      - "datanode2"
    ports:
      - 11090:11090
    expose:
      - 11090
    volumes:
      - ./TinyDFS:/dfs/TinyDFS
    restart: always